config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  resources :procedures
  resources :work_instructions
  resources :customers
  resources :parts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :parts
  validates :name, :customercode, :address, :city, :state, :zipcode, presence: true
  validates :state, length: { is: 2 }
  validates :zipcode, presence: true, length: { is: 5 }
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :customer
  belongs_to :procedure
  validates :name, :description, :price, :procedure_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  validates :name, :procedurecode, :presence => true
  validates :procedurecode, uniqueness: { case_sensitive: false }, length: { maximum: 4 }
  has_many :procedure_work_instructions
  has_many :parts
  has_many :work_instructions, :through => :procedure_work_instructions
  accepts_nested_attributes_for :work_instructions
end

app/models/procedure_work_instruction.rb
class ProcedureWorkInstruction < ApplicationRecord
  belongs_to :procedure
  belongs_to :work_instruction

end

app/models/work_instruction.rb
class WorkInstruction < ApplicationRecord
  validates :name, :description, :workcode, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :workcode, uniqueness: { case_sensitive: false }, length: { maximum: 4 }
  has_many :procedure_work_instructions
  has_many :procedures, through: :procedure_work_instructions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :find_customer, except: [:index, :new, :create]

  def index
    @customers = Customer.all
  end

  def show
    #Test commit
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    if @customer.save
      flash[:success] = 'Customer has been saved!'
      redirect_to @customer
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @customer.update_attributes(customer_params)
    if @customer.save
      flash[:success] = 'Customer has been saved!'
      redirect_to @customer
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    @customer.destroy
    flash[:error] = 'Customer has been deleted!'
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:name,  :customercode, :address, :addressdetails, :city, :state, :zipcode)
  end

  def find_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
before_action :find_part, except: [:index, :new, :create]

  def index
    @part = Part.all.includes(:procedure, :customer)
  end

  def show
  end

  def new
    @part = Part.new
  end

  def create
    @part = Part.create(part_params)
    if @part.save
      flash[:success] = 'New Part has been created!'
      redirect_to parts_path
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @part.update_attributes(part_params)
    if @part.save
      flash[:success] = 'Part has been updated!'
      redirect_to @part
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    @part.destroy
    flash[:error] = 'Part has been deleted!'
    redirect_to parts_path
  end

  private
  def part_params
    params.require(:part).permit(:name, :description, :price, :procedure_id, :customer_id)
  end

  def find_part
    @part = Part.find(params[:id])
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  before_action :find_procedure, except: [:index, :new, :create]

  def index
    @procedure = Procedure.all
  end

  def show
  end

  def new
    @procedure = Procedure.new
    @procedure.work_instructions.build
  end

  def create
    @procedure = Procedure.create(procedure_params)
    add_work_instructions
    if @procedure.valid?
      flash[:success] = 'Procedure has been saved!'
      redirect_to @procedure
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def edit
  end


  def update
    @procedure = Procedure.find(params[:id])
    @procedure.update_attributes!(procedure_params)
    add_work_instructions
    if @procedure.valid?
      flash[:success] = 'Procedure has been updated!'
      redirect_to @procedure
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    find_procedure
    @procedure.destroy
    flash[:error] = 'Procedure has been deleted!'
    redirect_to root_path
  end
end

private

def procedure_params
  params.require(:procedure).permit(:name, :procedurecode, [:work_instructions_attributes => [:name, :id]] )
end

def find_procedure
  @procedure = Procedure.find(params[:id])
end

def add_work_instructions
  if @procedure.save
    (params[:procedure]['work_instruction_ids'].to_a).each do |work_instruction|
      if !work_instruction.empty?
        @procedure.procedure_work_instructions.create(:work_instruction_id => work_instruction)
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/work_instructions_controller.rb
class WorkInstructionsController < ApplicationController
  before_action :find_work_instruction, except: [:index, :new, :create]

  def index
    @work_instruction = WorkInstruction.all
  end

  def show
  end

  def new
    @work_instruction = WorkInstruction.new
  end

  def create
    @work_instruction = WorkInstruction.create(work_instruction_params)
    if @work_instruction.save
      flash[:success] = 'Instructions have been saved!'
      redirect_to work_instructions_path
    else
      render :new, :status => :unprocessable_entity
    end
  end


  def edit
  end

  def update
    @work_instruction.update_attributes(work_instruction_params)
    if @work_instruction.save
      flash[:success] = 'Instructions have been saved!'
      redirect_to @work_instruction
    else
      render :edit, :status => :unprocessable_entity
    end
  end


  def destroy
    @work_instruction.destroy
    flash[:error] = 'Work Instruction has been deleted!'
    redirect_to root_path
  end


  private

  def work_instruction_params
    params.require(:work_instruction).permit(:name, :workcode, :description)
  end

  def find_work_instruction
    @work_instruction = WorkInstruction.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/work_instructions_helper.rb
module WorkInstructionsHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer do |f| %>
<%= f.input :name, label: "Name" %>
<%= f.input :customercode, label: 'Customer Code'  %>
<%= f.input :address, label: 'Address line 1' %>
<%= f.input :addressdetails, label: 'Address line 2' %>
<%= f.input :city %>
<%= f.input :state %>
<%= f.input :zipcode, label: 'Zip' %>
<br  />
<%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/customers/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Edit Customer Info</h2>
  <%= render "form" %>
    <%= link_to 'Delete Record', customer_path(@customer), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this?' }, :class => 'btn btn-danger' %>
</div>

app/views/customers/index.html.erb
<!--<table class="table-striped col-xs-12">
  <tr>
    <th><b>Name</b></th>
    <th><b>Customer Code</b></th>
    <th><b>Address 1</b></th>
    <th><b>Address 2</b></th>
    <th><b>City</b></th>
    <th><b>State</b></th>
    <th><b>Zip Code</b></th>
    <th><b>More Info?</b></th>
    <th>
  </tr>
  <% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= customer.customercode %></td>
    <td><%= customer.address %></td>
    <td><%= customer.addressdetails %></td>
    <td><%= customer.city %></td>
    <td><%= customer.state %></td>
    <td><%= customer.zipcode %></td>
    <td><%= link_to 'More Info', customer_path(customer), class: 'btn btn-primary btn-md' %></td>

  </tr>
  <% end %>
  </table>
-->

<%= react_component 'Customers', {customers: @customers.as_json(only: [:id, :name, :customercode, :address, :addressdetails, :city, :state, :zipcode ]) } %>

app/views/customers/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Add a New Customer</h2>
  <%= render "form" %>
</div>

app/views/customers/show.html.erb
<!--<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2><%= @customer.name %></h2>
  <table class="table">
    <tr class ="active">
      <td><b>Customer Code:</b> <%= @customer.customercode %></td>
      <td><b>Address 1:</b> <%= @customer.address %></td>
      <td><b>Address 2: </b><%= @customer.addressdetails %></td>
    </tr>
    <tr class ="default">
      <td><b>City: </b><%= @customer.city %></td>
      <td><b>State: </b><%= @customer.state %></td>
      <td><b>Zipcode: </b><%= @customer.zipcode%></td>
    </tr>
  </table>
-->
<%= react_component 'Customer', {customer: @customer.as_json(only: [:id, :name, :customercode, :address, :addressdetails, :city, :state, :zipcode]) } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Order Manager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Shop Manager', root_path, class: 'navbar-brand' %>/li>

      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'New Work Instruction', new_work_instruction_path %></li>
          <li><%= link_to 'New Procedure', new_procedure_path %></li>
          <li><%= link_to 'New Customer', new_customer_path %></li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
        <ul class="nav navbar-nav navbar-right">

          <li><a href="#">Link</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

  </body>
  </html>

app/views/parts/_form.html.erb
<%= simple_form_for @part do |f| %>
<table>
  <tr><%= f.input :name, label: 'Name' %></tr>
  <tr><%= f.input :description, label: 'Description' %></tr>
  <td><%= f.input :price, label: 'Price' %></td>
    <td><b> Customer:</b>  <%= f.collection_select :customer_id, Customer.all, :id, :name, label: 'Select a Customer' %></td>
      <td><b> Procedure</b><%= f.collection_select :procedure_id, Procedure.all, :id, :name, label: 'Select a Procedure' %></td>

</table>
<table>


</table>
<%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/parts/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Edit Customer Info</h2>
  <%= render "form" %>
  <br />
  <td><%= link_to 'Delete', part_path(@part), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
</div>

app/views/parts/index.html.erb
<table class="table-striped col-xs-12">
  <tr>
    <th><b>Name</b></th>
    <th><b>Description</b></th>
    <th><b>Procedure</b></th>
    <th><b>Price</b></th>
    <th><b>Customer</b></th>
    <th>
    <th>
  </tr>
  <% @part.each do |part| %>
  <tr>
    <td><%= part.name %></td>
    <td><%= part.description %></td>
    <td><%= part.procedure.name %></td>
    <td><%= part.price %></td>
    <td><%= part.customer.name %></td>
    <td><%= link_to 'More Info', part_path(part), class: 'btn btn-primary btn-md' %></td>

  </tr>
  <% end %>

app/views/parts/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Add a New Part</h2>
  <%= render "form" %>
</div>

app/views/parts/show.html.erb
<table class="table-striped col-xs-12">
  <tr>
    <th><b>Name</b></th>
    <th><b>Description</b></th>
    <th><b>Procedure</b></th>
    <th><b>Price</b></th>
    <th><b>Customer</b></th>
    <th><b>Edit?</b></th>
    <th>
    <th>
  </tr>

  <tr>
    <td><%= @part.name %></td>
    <td><%= @part.description %></td>
    <td><%= @part.procedure.name %></td>
    <td><%= @part.price %></td>
    <td><%= @part.customer.name %></td>
    <td><%= link_to 'Edit Part', edit_part_path(@part), class: 'btn btn-primary btn-md' %></td>

  </tr>

app/views/procedures/_form.html.erb
<%= simple_form_for @procedure do |f| %>
<%= f.input :name, label: "Name" %>
<%= f.input :procedurecode, label: "Code" %>

<table>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
</table>

<table>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
</table>

<table>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
  <td><%= f.association :work_instructions, as: :select, allow_blank: :true %></td>
</table>

<%= f.submit "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/procedures/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Edit Procedure</h2>
  <%= render "form" %>
  <br />
    <%= link_to 'Delete Record', procedure_path(@procedure), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this record?' }, :class => 'btn btn-danger' %>
</div>

app/views/procedures/index.html.erb
<table class="table-striped col-xs-12">
  <tr>
    <th><b>Name</b></th>
    <th><b>Procedure Code</b></th>
    <th>
  </tr>
  <% @procedure.each do |procedure| %>
  <tr>
    <td><%= procedure.name %></td>
    <td><%= procedure.procedurecode %></td>
    <td><%= link_to 'More Info', procedure_path(procedure), class: 'btn btn-primary btn-md' %></td>

  </tr>
  <% end %>

app/views/procedures/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Add a New Procedure</h2>
  <%= render "form" %>
</div>

app/views/procedures/show.html.erb
<h2><%= @procedure.name %></h2>
<h4>Work Instructions</h4>
<table class="table-striped col-xs-10">
  <tr>
    <th><b>Name</b></th>
    <th><b>Code</b></th>
    <th><b>Description</b></th>
  </tr>
  <% @procedure.work_instructions.each do |work_instruction| %>
  <tr>
    <td><%= work_instruction.name %></td>
    <td><%= work_instruction.workcode %></td>
    <td><%= work_instruction.description %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Edit Procedure', edit_procedure_path(@procedure), class: 'btn btn-primary btn-md' %>

app/views/static_pages/index.html.erb
<h2><%= link_to 'Customer List', customers_path %></h2>
<h2><%= link_to 'Procedure List', procedures_path %></h2>
<h2><%= link_to 'Work Instruction List', work_instructions_path %></h2>

app/views/work_instructions/_form.html.erb
<%= simple_form_for @work_instruction do |f| %>
<%= f.input :name, label: "Name" %>
<%= f.input :workcode, label: "Code" %>
<%= f.input :description, label: "Description" %>
<%= f.submit "Submit", class: 'btn btn-primary' %>

<% end %>

app/views/work_instructions/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Edit Work Instruction</h2>
  <%= render "form" %>
  <br />
    <%= link_to 'Delete Record', work_instruction_path(@work_instruction), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this record?' }, :class => 'btn btn-danger' %>
</div>

app/views/work_instructions/index.html.erb
<table class="table-striped col-xs-12">
  <tr>
    <th><b>Name</b></th>
    <th><b>Code</b></th>
    <th><b>Description</b></th>
    <th><b>More Info?</b></th>
    <th>
    </tr>
    <% @work_instruction.each do |work_instruction| %>
    <tr>
      <td><%= work_instruction.name %></td>
      <td><%= work_instruction.workcode %></td>
      <td><%= work_instruction.description %></td>
      <td><%= link_to 'More Info', work_instruction_path(work_instruction), class: 'btn btn-primary btn-md' %></td>

    </tr>
    <% end %>

app/views/work_instructions/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h2 class="text-center">Add a New Work Instruction</h2>
  <%= render "form" %>
</div>

app/views/work_instructions/show.html.erb
<table class="table-striped col-xs-12">
  <tr>
    <th><b>Name</b></th>
    <th><b>Code</b></th>
    <th><b>Description</b></th>
    <th><b>Edit?</b></th>
<tr>
  <td><%= @work_instruction.name %></td>
  <td><%= @work_instruction.workcode %></td>
  <td><%= @work_instruction.description %></td>
  <td><%= link_to 'Edit', edit_work_instruction_path(@work_instruction), class: 'btn btn-primary btn-md' %></td>
  </tr>
</table>